name: Publishes package to Github Packages
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        name: Checkouts sources
      - uses: actions/setup-java@v2
        name: Sets up JDK 16
        with:
          java-version: '16'
          distribution: 'adopt'
      - uses: burrunan/gradle-cache-action@v1
        name: Publishes with Gradle (cached)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: publish
          gradle-version: wrapper